"""empty message

Revision ID: 1d6f8030164b
Revises: 7821b2ea5fcf
Create Date: 2024-04-16 12:08:53.502401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d6f8030164b'
down_revision: Union[str, None] = '7821b2ea5fcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'invite_registation', ['id'])
    op.create_unique_constraint(None, 'permissions', ['id'])
    op.create_unique_constraint(None, 'project', ['id'])
    op.create_unique_constraint(None, 'roles', ['id'])
    op.create_unique_constraint(None, 'tag', ['id'])
    op.alter_column('users', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'tag', type_='unique')
    op.drop_constraint(None, 'roles', type_='unique')
    op.drop_constraint(None, 'project', type_='unique')
    op.drop_constraint(None, 'permissions', type_='unique')
    op.drop_constraint(None, 'invite_registation', type_='unique')
    # ### end Alembic commands ###
